# -*- coding: utf-8 -*-
"""artigo2up.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlK6WuPz4wLLBCslypYo-NfquzewLxEQ
"""

import matplotlib.pyplot as plt
import numpy as np

metrics = ['Accuracy', 'Recall (Bad Payer)', 'F1-Score']
rf_scores = [0.8824, 0.82, 0.88]
mlp_scores = [0.8776, 0.78, 0.88]

x = np.arange(len(metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(8, 5))
rects1 = ax.bar(x - width/2, rf_scores, width, label='Random Forest', color='#404040')
rects2 = ax.bar(x + width/2, mlp_scores, width, label='MLP (Neural Network)', color='#D3D3D3')

ax.set_ylabel('Scores')
ax.set_title('Performance Comparison by Metric')
ax.set_xticks(x)
ax.set_xticklabels(metrics)
ax.set_ylim(0.7, 1.0)
ax.legend(loc='lower right')

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)

fig.tight_layout()
plt.savefig('comparison_chart_ieee.png')
plt.show()