# -*- coding: utf-8 -*-
"""artigo2up.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlK6WuPz4wLLBCslypYo-NfquzewLxEQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay

sns.set(style="whitegrid")

file_name = 'p34.xlsx'

try:
    if file_name.endswith('.xlsx'):
        df = pd.read_excel(file_name)
    else:
        try:
            df = pd.read_csv(file_name)
        except:
            df = pd.read_csv(file_name, sep=';')
except Exception as e:
    try:
        df = pd.read_excel('p34.xlsx')
    except:
        pass

if 'cliente' in df.columns:
    df = df.drop(columns=['cliente'])

label_encoders = {}
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Matriz de Correlação das Variáveis")
plt.savefig("correlacao.png")
plt.show()

target_col = 'STATUS'
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Rede Neural MLP": MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, activation='relu', solver='adam', random_state=42)
}

results = {}

for name, model in models.items():

    X_train_run = X_train_scaled if "Neural" in name else X_train
    X_test_run = X_test_scaled if "Neural" in name else X_test

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, X_train_run, y_train, cv=cv, scoring='accuracy')
    print(f"Acurácia Média (Cross-Validation 5-fold): {cv_scores.mean():.4f} (+/- {cv_scores.std()*2:.4f})")

    model.fit(X_train_run, y_train)

    y_pred = model.predict(X_test_run)

    acc = accuracy_score(y_test, y_pred)
    print(f"Acurácia no Teste (Holdout): {acc:.4f}")
    print("\nRelatório de Classificação:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Bom', 'Mau'])

    fig, ax = plt.subplots(figsize=(6, 5))
    disp.plot(cmap='Blues', ax=ax, values_format='d')
    plt.title(f'Matriz de Confusão - {name}')
    plt.grid(False)
    plt.savefig(f"confusion_matrix_{name.replace(' ', '_')}.png")
    plt.show()
